language: ruby
sudo: false
script:
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter

matrix:
  include:

    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4.0

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-3.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.1

    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.1
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.2

    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-4.1
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-4.2

    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.rails-4.1
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.rails-4.2
